title: "Yufan Zheng_Academic profile"
baseURL: "https://yufanivanzheng.github.io/"
languageCode: "en-us"
defaultContentLanguage: "en"
theme: ["wowchemy"]

menu:
  main:
   - name: About
     url: '#about'
     weight: 10
   - name: Publications
     url: '#publications'
     weight: 20
   - name: Projects
     url: '#projects'
     weight: 30
   - name: Contact
     url: '#contact'
     weight: 40

module:
imports:
- path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy

params:
name: "Yufan (Ivan) Zheng"
role: "Postdoctoral Fellow"
organization: "National Institutes of Allergic and Infectious Diseases"
location: "Bethesda, MD, US"

email: "ivanyufanzheng@email.com"
phone: "+86 301 906 8663"

social:
- icon: academic
icon_pack: fas
link: "/cv.pdf"
- icon: envelope
icon_pack: fas
link: "mailto:your@email.com"
- icon: github
icon_pack: fab
link: "https://github.com/YufanIvanZheng"
- icon: linkedin
icon_pack: fab
link: "https://www.linkedin.com/in/YufanIvanZheng"

homepage:
sections:
- about
- publications
- projects
- contact

############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/author/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 80
  anchor: smart
timeout: 600000
taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types
markup:
  _merge: deep
  highlight:
    lineNos: false
security:
  _merge: deep
sitemap:
  _merge: deep
